#!/usr/bin/python2
#coding:utf-8
#响应状态
SUCCEED=1
ERROR=0
#对replayer的操作类型
SET_SEGMENT = 0
SET_MANAGER = 1
SET_TRACE = 2
START_REPLAY= 3

#对MergeSpeedController操作类型
REPORT_DIRECT_IN = 0
REPORT_DIRECT_OUT = 1
REPORT_BUFFER_IN = 2
REPORT_BUFFER_OUT = 3
REPORT_STORAGE = 6
GET_IN = 4
GET_OUT = 5

#log merger
ADD_SEGMENT = 0
REMOVE_SEGMENT = 1

#对forwarding process/ proxy操作类型
READ=0
WRITE=1
SWITCH_ZOMBIE=2
PULL_LOG = 3
SET_LOG_HEAD = 4
PROBE_STATE = 5
GET_FINISHED_WRITE = 6
GET_FINISHED_READ = 7
GET_LOG_HEAD = 8
REPORT_IN_QUEUE_WRITE = 9
REPORT_IN_QUEUE_READ = 10
CREATE_PROXY = 11
ADD_SHARED_QUEUE_SIZE = 12
SUB_SHARED_QUEUE_SIZE = 13
TRAVERSE_CHAIN_REPLICA = 14

#Strip是否已经写满了
FULL = 0
UNFULL = 1

#log元数据状态
VALID = 0 
OBSELETE = 1

#Manager支持操作
INIT_BUFFER_PROCESS = 0
INIT_FORWARDING_PROCESS = 1
NOTIFY_FORWARDING_PROCESS_PORT = 3
NOTIFY_FORWARDING_PROXY_PORT = 4
INIT_LOG_MERGER = 5
INIT_REPLAYER = 6
NOTIFY_REPLAYER_READY = 7
START_REPLAYER = 8
GET_SEGMENT_INFO = 9
GET_LOG_MERGER_PORT = 10
GET_BUFFER_PROXY_INFO = 11
GET_TRACE_PATH = 12
GET_LOG_PATH = 13
GET_REPLAYER_PORT = 14
GET_FORWARDING_PROXY_INFO = 15
SHUTDOWN_BUFFER_PROCESS = 16
SHUTDOWN_REQ_PROCESS = 17
SHUTDOWN_LOG_MERGER = 18
GET_SERVER_SEGMENT_INFO = 19
REPORT_LOAD = 20
NOTIFY_BUFFER_PROCESS_PORT = 21
NOTIFY_BUFFER_PROXY_PORT = 22
RESET_SYS = 23
RESTRICT_BANDWIDTH = 24
UNRESTRICT_BANDWIDTH = 25
CLEAN_SYS = 26
STOP_SEG_SCHEDULE = 27
REPORT_STABLE_BANDWIDTH = 28
GET_FREE_BANDWIDTH = 29
GET_SCHEDULE_COUNT = 30
NOTIFY_STORAGE_SERVER_ID = 31
INIT_STORAGE_SERVER = 32
INIT_MERGE_SPEED_CONTROLLER = 33
SHUTDOWN_MANAGER = 34


#Buffer Process/ Proxy支持操作
BUFFER_WRITE= 0
BUFFER_READ= 1
GET_BUFFER_FINISHED_READ = 2
GET_BUFFER_FINISHED_WRITE = 3
GET_SEGMENT_LOG_HEAD = 4
SEGMENT_LOG_META_READ = 5
BUFFER_REMOVE = 6
BUFFER_PULL = 7
GET_LOG_ENTRY = 8
STOP_GET_LOG_ENTRY = 9
PULL_LOG_ENTRY = 10
REPORT_BUFFER_IN_QUEUE_READ = 11
REPORT_BUFFER_IN_QUEUE_WRITE = 12
CREATE_ENGINE = 13

#Storage Server支持操作
STORAGE_READ = 0
STORAGE_WRITE = 1
STORAGE_GET_FINISHED_WRITE = 2
STORAGE_GET_FINISHED_READ = 3
REGISTER_SEGMENT = 4
UNREGISTER_SEGMENT = 5
MERGE_LOG = 6
GET_MERGE_LOG_HEAD = 7
START_SUBSCRIBE_MSC = 8
END_SUBSCRIBE_MSC = 9

#socket状态
FREE =0 
USED=1
#req server状态
ALIVE = 0
ZOMBIE = 1
STOP_WORK = 3
#关进程信号
SHUTDOWN = 30